### ISSUE TITLE
Appstream data contains referenced to cached icons that are not available

### ISSUE THREAD

**Issue by robert-ancell** [canonical/appstream-cloud#1]
Appstream data on Ubuntu lists icons that don't seem to be available.

For example from `/var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_jammy_universe_dep11_Components-amd64.yml.gz`:
```
---
Type: desktop-application
ID: accerciser.desktop
Package: accerciser
...
Icon:
  cached:
  - name: accerciser_accerciser.png
    width: 48
    height: 48
  - name: accerciser_accerciser.png
    width: 64
    height: 64
  - name: accerciser_accerciser.png
    width: 128
    height: 128
  stock: accerciser
  remote:
  - url: a/ac/accerciser.desktop/C8EF0328A39CA1719B7795A012A7B6C6/icons/128x128/accerciser_accerciser.png
    width: 128
    height: 128
```

This refers to a 128x128 pixel icon, but looking at the icon locations only the 48x48 and 64x64 icons seem to be installed:
```
$ ls /var/lib/app-info/icons/ubuntu-jammy-universe/ 
48x48  64x64  64x64@2
```

This is causing recent versions of GNOME Software to show no icons on the details page for these apps, as it tries to get the larger resolution icon (128x128) and then fails to find it.

Possible reasons why this is occurring:
- The 128x128 icon is actually the 64x64@2 icon but the directory has the wrong name.
- The higher resolution icons aren't being distributed by us for some reason.
- I don't have all the icons installed for some reason.
